/**
 * Topaz API
 * ## Topaz API Spec  To get up and running with Topaz API as quickly as possible, read through these docs.  ### Prerequisites  Create an account at [https://topaz.io](https://topaz.io), log in, and generate an API Token.  You'll need an API Token to create a new app, create objects, create hashes, and view proofs.  All API requests should be prefixed with `/v1`, indicating that you're targeting version 1 of our API.  ### Guarantee  Topaz API follows Semantic Versioning (https://semver.org), so expect that any breaking changes will be versioned under a new route prefix.
 *
 * OpenAPI spec version: 0.1.17
 * Contact: hello@topaz.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

'use strict';

const ApiClient = require('../ApiClient');


/**
 * The AppCommon model module.
 * @module model/AppCommon
 * @version 0.1.17
 */

/**
 * Constructs a new <code>AppCommon</code>.
 * The properties that are shared amongst all versions of the App model.
 * @alias module:model/AppCommon
 * @class
 * @param name {String} 
 * @param interval {Number} 
 */
var exports = function(name, interval) {
  var _this = this;

  _this['name'] = name;
  _this['interval'] = interval;
};

/**
 * Constructs a <code>AppCommon</code> from a plain JavaScript object, optionally creating a new instance.
 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
 * @param {Object} data The plain JavaScript object bearing properties of interest.
 * @param {module:model/AppCommon} obj Optional instance to populate.
 * @return {module:model/AppCommon} The populated <code>AppCommon</code> instance.
 */
exports.constructFromObject = function(data, obj) {
  if (data) {
    obj = obj || new exports();

    if (data.hasOwnProperty('name')) {
      obj['name'] = ApiClient.convertToType(data['name'], 'String');
    }
    if (data.hasOwnProperty('interval')) {
      obj['interval'] = ApiClient.convertToType(data['interval'], 'Number');
    }
  }
  return obj;
}

/**
 * @member {String} name
 */
exports.prototype['name'] = undefined;
/**
 * @member {Number} interval
 */
exports.prototype['interval'] = undefined;


module.exports = exports;
