/**
 * Topaz API
 * ## Topaz API Spec  To get up and running with Topaz API as quickly as possible, read through these docs.  ### Prerequisites  Create an account at [https://topaz.io](https://topaz.io), log in, and generate an API Token.  You'll need an API Token to create a new app, create objects, create hashes, and view proofs.  All API requests should be prefixed with `/v1`, indicating that you're targeting version 1 of our API.  ### Guarantee  Topaz API follows Semantic Versioning (https://semver.org), so expect that any breaking changes will be versioned under a new route prefix.
 *
 * OpenAPI spec version: 0.1.17
 * Contact: hello@topaz.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

'use strict';

const AppOutput = require('./AppOutput');


/**
 * The AppOutputDetailed model module.
 * @module model/AppOutputDetailed
 * @version 0.1.17
 */

/**
 * Constructs a new <code>AppOutputDetailed</code>.
 * The properties that are included when fetching a single Object.
 * @alias module:model/AppOutputDetailed
 * @class
 * @implements module:model/AppOutput
 * @param id {String} 
 * @param userId {String} 
 * @param name {String} 
 * @param interval {Number} 
 */
var exports = function(id, userId, name, interval) {
  var _this = this;

  AppOutput.call(_this, name, interval, id, userId);
};

/**
 * Constructs a <code>AppOutputDetailed</code> from a plain JavaScript object, optionally creating a new instance.
 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
 * @param {Object} data The plain JavaScript object bearing properties of interest.
 * @param {module:model/AppOutputDetailed} obj Optional instance to populate.
 * @return {module:model/AppOutputDetailed} The populated <code>AppOutputDetailed</code> instance.
 */
exports.constructFromObject = function(data, obj) {
  if (data) {
    obj = obj || new exports();

    AppOutput.constructFromObject(data, obj);
  }
  return obj;
}


// Implement AppOutput interface:
/**
 * @member {String} name
 */
exports.prototype['name'] = undefined;

/**
 * @member {Number} interval
 */
exports.prototype['interval'] = undefined;

/**
 * @member {String} id
 */
exports.prototype['id'] = undefined;

/**
 * @member {String} userId
 */
exports.prototype['userId'] = undefined;


module.exports = exports;
