/**
 * Topaz API
 * ## Topaz API Spec  To get up and running with Topaz API as quickly as possible, read through these docs.  ### Prerequisites  Create an account at [https://topaz.io](https://topaz.io), log in, and generate an API Token.  You'll need an API Token to create a new app, create objects, create hashes, and view proofs.  All API requests should be prefixed with `/v1`, indicating that you're targeting version 1 of our API.  ### Guarantee  Topaz API follows Semantic Versioning (https://semver.org), so expect that any breaking changes will be versioned under a new route prefix.
 *
 * OpenAPI spec version: 0.1.17
 * Contact: hello@topaz.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/HashstuboutputHashes'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./HashstuboutputHashes'));
  } else {
    // Browser globals (root is window)
    if (!root.TopazApi) {
      root.TopazApi = {};
    }
    root.TopazApi.HashStubOutput = factory(root.TopazApi.ApiClient, root.TopazApi.HashstuboutputHashes);
  }
}(this, function(ApiClient, HashstuboutputHashes) {
  'use strict';




  /**
   * The HashStubOutput model module.
   * @module model/HashStubOutput
   * @version 0.1.17
   */

  /**
   * Constructs a new <code>HashStubOutput</code>.
   * Hash stub consisting of ID and Hash value
   * @alias module:model/HashStubOutput
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>HashStubOutput</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HashStubOutput} obj Optional instance to populate.
   * @return {module:model/HashStubOutput} The populated <code>HashStubOutput</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('hashes')) {
        obj['hashes'] = ApiClient.convertToType(data['hashes'], [HashstuboutputHashes]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/HashstuboutputHashes>} hashes
   */
  exports.prototype['hashes'] = undefined;



  return exports;
}));


