/**
 * Topaz API
 * ## Topaz API Spec  To get up and running with Topaz API as quickly as possible, read through these docs.  ### Prerequisites  Create an account at [https://topaz.io](https://topaz.io), log in, and generate an API Token.  You'll need an API Token to create a new app, create objects, create hashes, and view proofs.  All API requests should be prefixed with `/v1`, indicating that you're targeting version 1 of our API.  ### Guarantee  Topaz API follows Semantic Versioning (https://semver.org), so expect that any breaking changes will be versioned under a new route prefix.
 *
 * OpenAPI spec version: 0.1.17
 * Contact: hello@topaz.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TopazApi) {
      root.TopazApi = {};
    }
    root.TopazApi.HashCommon = factory(root.TopazApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The HashCommon model module.
   * @module model/HashCommon
   * @version 0.1.17
   */

  /**
   * Constructs a new <code>HashCommon</code>.
   * The properties that are shared amongst all versions of the Hash model.
   * @alias module:model/HashCommon
   * @class
   * @param hash {String} 
   */
  var exports = function(hash) {
    var _this = this;

    _this['hash'] = hash;
  };

  /**
   * Constructs a <code>HashCommon</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HashCommon} obj Optional instance to populate.
   * @return {module:model/HashCommon} The populated <code>HashCommon</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('hash')) {
        obj['hash'] = ApiClient.convertToType(data['hash'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} hash
   */
  exports.prototype['hash'] = undefined;



  return exports;
}));


