/**
 * Topaz API
 * ## Topaz API Spec  To get up and running with Topaz API as quickly as possible, read through these docs.  ### Prerequisites  Create an account at [https://topaz.io](https://topaz.io), log in, and generate an API Token.  You'll need an API Token to create a new app, create objects, create hashes, and view proofs.  All API requests should be prefixed with `/v1`, indicating that you're targeting version 1 of our API.  ### Guarantee  Topaz API follows Semantic Versioning (https://semver.org), so expect that any breaking changes will be versioned under a new route prefix.
 *
 * OpenAPI spec version: 0.1.17
 * Contact: hello@topaz.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/HashStubOutput', 'model/HashstuboutputHashes', 'model/ProofOutput'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./HashStubOutput'), require('./HashstuboutputHashes'), require('./ProofOutput'));
  } else {
    // Browser globals (root is window)
    if (!root.TopazApi) {
      root.TopazApi = {};
    }
    root.TopazApi.ProofOutputDetailed = factory(root.TopazApi.ApiClient, root.TopazApi.HashStubOutput, root.TopazApi.HashstuboutputHashes, root.TopazApi.ProofOutput);
  }
}(this, function(ApiClient, HashStubOutput, HashstuboutputHashes, ProofOutput) {
  'use strict';




  /**
   * The ProofOutputDetailed model module.
   * @module model/ProofOutputDetailed
   * @version 0.1.17
   */

  /**
   * Constructs a new <code>ProofOutputDetailed</code>.
   * The properties that are included when fetching a single Proof.
   * @alias module:model/ProofOutputDetailed
   * @class
   * @implements module:model/ProofOutput
   * @implements module:model/HashStubOutput
   * @param id {String} 
   * @param merkleRoot {String} 
   * @param ethTransaction {String} 
   * @param unixTimestamp {Number} 
   * @param appId {String} 
   */
  var exports = function(id, merkleRoot, ethTransaction, unixTimestamp, appId) {
    var _this = this;

    ProofOutput.call(_this, id, merkleRoot, ethTransaction, unixTimestamp, appId);
    HashStubOutput.call(_this);
  };

  /**
   * Constructs a <code>ProofOutputDetailed</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProofOutputDetailed} obj Optional instance to populate.
   * @return {module:model/ProofOutputDetailed} The populated <code>ProofOutputDetailed</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      ProofOutput.constructFromObject(data, obj);
      HashStubOutput.constructFromObject(data, obj);
    }
    return obj;
  }


  // Implement ProofOutput interface:
  /**
   * @member {String} id
   */
exports.prototype['id'] = undefined;

  /**
   * @member {String} merkleRoot
   */
exports.prototype['merkleRoot'] = undefined;

  /**
   * @member {String} ethTransaction
   */
exports.prototype['ethTransaction'] = undefined;

  /**
   * @member {Number} unixTimestamp
   */
exports.prototype['unixTimestamp'] = undefined;

  /**
   * @member {String} appId
   */
exports.prototype['appId'] = undefined;

  // Implement HashStubOutput interface:
  /**
   * @member {Array.<module:model/HashstuboutputHashes>} hashes
   */
exports.prototype['hashes'] = undefined;



  return exports;
}));


