/**
 * Topaz API
 * ## Topaz API Spec  To get up and running with Topaz API as quickly as possible, read through these docs.  ### Prerequisites  Create an account at [https://topaz.io](https://topaz.io), log in, and generate an API Token.  You'll need an API Token to create a new app, create objects, create hashes, and view proofs.  All API requests should be prefixed with `/v1`, indicating that you're targeting version 1 of our API.  ### Guarantee  Topaz API follows Semantic Versioning (https://semver.org), so expect that any breaking changes will be versioned under a new route prefix.
 *
 * OpenAPI spec version: 0.1.17
 * Contact: hello@topaz.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ObjectOutput', 'model/ObjectOutputDetailed'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ObjectOutput'), require('../model/ObjectOutputDetailed'));
  } else {
    // Browser globals (root is window)
    if (!root.TopazApi) {
      root.TopazApi = {};
    }
    root.TopazApi.ObjectsApi = factory(root.TopazApi.ApiClient, root.TopazApi.ObjectOutput, root.TopazApi.ObjectOutputDetailed);
  }
}(this, function(ApiClient, ObjectOutput, ObjectOutputDetailed) {
  'use strict';

  /**
   * Objects service.
   * @module api/ObjectsApi
   * @version 0.1.17
   */

  /**
   * Constructs a new ObjectsApi. 
   * @alias module:api/ObjectsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createObject operation.
     * @callback module:api/ObjectsApi~createObjectCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ObjectOutputDetailed} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create Object
     * Creating a new &#x60;object&#x60; doesn&#39;t take any body data in its request.
     * @param {String} appId 
     * @param {module:api/ObjectsApi~createObjectCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ObjectOutputDetailed}
     */
    this.createObject = function(appId, callback) {
      var postBody = null;

      // verify the required parameter 'appId' is set
      if (appId === undefined || appId === null) {
        throw new Error("Missing the required parameter 'appId' when calling createObject");
      }


      var pathParams = {
        'appId': appId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['API Key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ObjectOutputDetailed;

      return this.apiClient.callApi(
        '/apps/{appId}/objects', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the findObjects operation.
     * @callback module:api/ObjectsApi~findObjectsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/ObjectOutput>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List Objects
     * This endpoint will return all &#x60;objects&#x60; registered for an &#x60;app&#x60;.
     * @param {String} appId 
     * @param {module:api/ObjectsApi~findObjectsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/ObjectOutput>}
     */
    this.findObjects = function(appId, callback) {
      var postBody = null;

      // verify the required parameter 'appId' is set
      if (appId === undefined || appId === null) {
        throw new Error("Missing the required parameter 'appId' when calling findObjects");
      }


      var pathParams = {
        'appId': appId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['API Key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [ObjectOutput];

      return this.apiClient.callApi(
        '/apps/{appId}/objects', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getObject operation.
     * @callback module:api/ObjectsApi~getObjectCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ObjectOutputDetailed} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Object
     * This endpoint will return details about a single object, given the &#x60;objectId&#x60; passed in as the request parameter
     * @param {String} appId 
     * @param {String} objectId 
     * @param {module:api/ObjectsApi~getObjectCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ObjectOutputDetailed}
     */
    this.getObject = function(appId, objectId, callback) {
      var postBody = null;

      // verify the required parameter 'appId' is set
      if (appId === undefined || appId === null) {
        throw new Error("Missing the required parameter 'appId' when calling getObject");
      }

      // verify the required parameter 'objectId' is set
      if (objectId === undefined || objectId === null) {
        throw new Error("Missing the required parameter 'objectId' when calling getObject");
      }


      var pathParams = {
        'appId': appId,
        'objectId': objectId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['API Key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = ObjectOutputDetailed;

      return this.apiClient.callApi(
        '/apps/{appId}/objects/{objectId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
