/**
 * Topaz API
 * ## Topaz API Spec  To get up and running with Topaz API as quickly as possible, read through these docs.  ### Prerequisites  Create an account at [https://topaz.io](https://topaz.io), log in, and generate an API Token.  You'll need an API Token to create a new app, create objects, create hashes, and view proofs.  All API requests should be prefixed with `/v1`, indicating that you're targeting version 1 of our API.  ### Guarantee  Topaz API follows Semantic Versioning (https://semver.org), so expect that any breaking changes will be versioned under a new route prefix.
 *
 * OpenAPI spec version: 0.1.17
 * Contact: hello@topaz.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../helpers/setup', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../helpers/setup'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.setup, root.TopazApi);
  }
}(this, function(expect, setup, TopazApi) {
  'use strict';

  describe.only('AppsApi', function() {
    let instance;

    beforeEach('get a fresh api instance', function() {
      return setup.freshInstance()
        .then(instance = new TopazApi.AppsApi())
        .catch(err => console.error(err));
    });

    describe('createApp', function() {
      it('should call createApp successfully', function(done) {
        const input = new TopazApi.AppInput("my first app", 3600);
        instance.createApp({ body: input }, function(_, data, response) {
          expect(data.name).to.be(input.name);
          expect(data.interval).to.be(input.interval);
          expect(response.statusCode).to.be(201);
          done();
        });
      });
    });

    describe('findApps', function() {
      it('should call findApps successfully', function(done) {
        instance.createApp({ body: new TopazApi.AppInput("my first app", 3600) }, function() {
          instance.createApp({ body: new TopazApi.AppInput("my second app", 3600) }, function() {
            instance.findApps(function(_, data, response) {
              expect(data).to.have.length(2);
              expect(response.statusCode).to.be(200);
              done();
            });
          });
        });
      });
    });

    describe('getApp', function() {
      it('should call getApp successfully', function(done) {
        const input = new TopazApi.AppInput("my other app", 3600);
        instance.createApp({ body: input }, function(_, data, __) {
          const appId = data.id;
          instance.getApp(appId, function(_, data, response) {
            expect(data.id).to.be(appId);
            expect(data.name).to.be(input.name)
            expect(response.statusCode).to.be(200);
            done();
          });
        });
      });
    });
  });
}));
